version: '3.4'

services:

  zipkin:
    image: openzipkin/zipkin-slim:latest

  dapr-placement:
    image: "daprio/dapr:1.9.4"

  daprdotnetjourney.microservices.basket.api:
    image: cahityusuf/basketapi:v1.0.0
    #build:
    #  context: .
    #  dockerfile: Dockerfile.BasketApi

  daprdotnetjourney.microservices.basket.api.dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:daprdotnetjourney.microservices.basket.api"
    depends_on:
      - daprdotnetjourney.microservices.basket.api

  daprdotnetjourney.gateway.aggregator.api:
    image: cahityusuf/aggregatorapi:v1.0.0
    #build:
    #  context: .
    #  dockerfile: Dockerfile.Aggregator

  daprdotnetjourney.gateway.aggregator.api.dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:daprdotnetjourney.gateway.aggregator.api"
    depends_on:
      - daprdotnetjourney.gateway.aggregator.api

