version: '3.4'

volumes:
  redis:
  redisinsight:

services:

  redis:
    ports:
      - "5379:6379"
    volumes:
      - redis:/data

  redisinsight:
    ports:
      - 8081:8001
    volumes:
      - redisinsight:/db

  zipkin:
    ports:
      - "5411:9411"

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

  daprdotnetjourney.microservices.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5001:80"
      - "50001:50001"

  daprdotnetjourney.microservices.basket.api.dapr:
    command: ["./daprd",
      "-app-id", "basket-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  daprdotnetjourney.gateway.aggregator.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5002:80"
      - "50002:50002"

  daprdotnetjourney.gateway.aggregator.api.dapr:
    command: ["./daprd",
      "-app-id", "aggregator-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
