version: '3.4'

services:

  redis:
    image: redis:alpine

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest

  zipkin:
    image: openzipkin/zipkin-slim:latest

  dapr-placement:
    image: "daprio/dapr:1.9.4"

  daprdotnetjourney.microservices.basket.api:
    image: cahityusuf/basketapi:latest
    build:
      context: src/Microservices/BasketAPI/DaprDotNetJourney.Microservices.Basket.Api
      dockerfile: Dockerfile

  daprdotnetjourney.microservices.basket.api.dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:daprdotnetjourney.microservices.basket.api"
    depends_on:
      - daprdotnetjourney.microservices.basket.api

  daprdotnetjourney.gateway.aggregator.api:
    image: cahityusuf/aggregatorapi:latest
    build:
      context: src/Gateways/Aggregators/DaprDotNetJourney.Gateway.Aggregator.Api
      dockerfile: Dockerfile

  daprdotnetjourney.gateway.aggregator.api.dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:daprdotnetjourney.gateway.aggregator.api"
    depends_on:
      - daprdotnetjourney.gateway.aggregator.api

