apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: daprdotnetjourney
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: statestore.redis-enterprise-cluster.svc.cluster.local:13241
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
scopes:
  - basket-api
