apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi-deployment
  namespace: daprdotnetjourney
  labels:
    app: basketapi
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: basketapi
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: basketapi
        dapr.io/app-port: "80"
        dapr.io/config: "config"
      labels:
        app: basketapi
        service: basketapi
    spec:
      containers:
      - name: basketapi
        image: cahityusuf/basketapi:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.3"
          limits:
            memory: "2048Mi"
            cpu: "1"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80

